### PR TITLE
Add ed_label for LABEL support.

### PR DESCRIPTION
**Pull request by bmocm**

### CODE REVIEW

**Comment by yxliang01** [comment]
@bmocm @icy So is `ed_label` usable? Since there's no documentation for it...

**Comment by icy** [comment]
@yxliang01 it's to support LABEL instruction in Dockerfile, take a look at e.g. [1]. I haven't used LABEL in my practice  though.

[1] : https://docs.docker.com/engine/reference/builder/#label

**Comment by yxliang01** [comment]
Yup. I have been using `LABEL`. My question was whether the implementation for `ed_label` is complete and usable though. @icy Thanks.

**Comment by icy** [comment]
@yxliang01 It should work. However, please note that `bocker` expands any `$foo` variable when it executes and this may conflict with the design of Dockerfile. When you have such problem pls let me know. Thx

Example

```
echo "ed_label FOO=BAR; ed_bocker() { :; }" > test.tmp; bocker test.tmp; rm -fv test.tmp
###############################################################
# Dockerfile generated by Bocker-v1.3. Do not edit this file. #
###############################################################

FROM debian:wheezy
MAINTAINER Anh K. Huynh <kyanh@theslinux.org>

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Here is from `__ed_before_ship` method. You may need your own
# custom one to advance the base image when it doesn't have Bash.
#
# The default `__ed_before_ship` method is to print this message.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LABEL FOO=BAR
removed 'test.tmp'
```

**Comment by yxliang01** [comment]
Thanks a lot for your clarification! :)

**Pull request merged**
